### ISSUE TITLE
Cannot Obtain any planks

### ISSUE THREAD

**Issue by Multi-Coder-24** [brynblack/RealisticCraft#4]
I have used JEI to check for a recipe to gain planks but there is no recipe. I can see the saw but that requires a crafting table to make and you need planks to create the table

**Comment by lofilobzik** [comment]
From the [wiki of EarlyGame](https://jayceecreates.github.io/earlygame/wiki/?page=overview), shift and hold RMB on a log to create planks, and on a plank to create sticks

**Comment by Multi-Coder-24** [comment]
cheers lofilobzik
